### ISSUE TITLE
Routing doesn't work anymore

### ISSUE THREAD

**Issue by MaxiBoether** [gothinkster/node-express-realworld-example-app#37]
When running npm install & npm run dev, no routes work as  there's always an 404 error, no matter what route I try to open. 2 months ago this issue wasn't there.

Example:
```
Error: Not Found
    at D:\patenprogramm-backend\app.js:58:13
    at Layer.handle [as handle_request] (D:\patenprogramm-backend\node_modules\e
xpress\lib\router\layer.js:95:5)
    at trim_prefix (D:\patenprogramm-backend\node_modules\express\lib\router\ind
ex.js:312:13)
    at D:\patenprogramm-backend\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (D:\patenprogramm-backend\node_modules\express\li
b\router\index.js:330:12)
    at next (D:\patenprogramm-backend\node_modules\express\lib\router\index.js:2
71:10)
    at D:\patenprogramm-backend\node_modules\express\lib\router\index.js:618:15
    at next (D:\patenprogramm-backend\node_modules\express\lib\router\index.js:2
56:14)
    at Function.handle (D:\patenprogramm-backend\node_modules\express\lib\router
\index.js:176:3)
    at router (D:\patenprogramm-backend\node_modules\express\lib\router\index.js
:46:12)
    at Layer.handle [as handle_request] (D:\patenprogramm-backend\node_modules\e
xpress\lib\router\layer.js:95:5)
    at trim_prefix (D:\patenprogramm-backend\node_modules\express\lib\router\ind
ex.js:312:13)
    at D:\patenprogramm-backend\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (D:\patenprogramm-backend\node_modules\express\li
b\router\index.js:330:12)
    at next (D:\patenprogramm-backend\node_modules\express\lib\router\index.js:2
71:10)
    at Layer.handle [as handle_request] (D:\patenprogramm-backend\node_modules\e
xpress\lib\router\layer.js:91:12)
```

Does anyone here have the same problem and knows how to fix it? This is also happening for my app based on this repo, but as it happens with the current repo, I don't know what the problem is.

**Comment by MaxiBoether** [comment]
I'm dumb. You need to access it via /api/, forgot about that in the last 2 months

**Comment by arunkumarmn9** [comment]
seriously i didn't understand that.
what really you tried ?
