### ISSUE TITLE
Route.get() requires callback functions but got a [object Undefined]

### ISSUE THREAD

**Issue by coommark** [gothinkster/node-express-realworld-example-app#40]
I am attempting to recreate this application from scratch. So far I have users controller in place (without the articles, profiles and tags controllers.

However when I try to run the server, I get  `Route.get() requires callback functions but got a [object Undefined]` error. If I comment out the `router.get('/user'` and `router.put('/user'` routes, everything works okay and I can register users without problem.

I have been on this for hours. please does anyone know what the problem might be and how to fix it? Here is the complete code for the users controller:

`var mongoose = require('mongoose');
var router = require('express').Router();
var passport = require('passport');
var User = mongoose.model('User');
var auth = require('../auth');
var randomNumber = require('../../config/randomNumberGenerator');

router.get('/user', auth.required, function(req, res, next){
  User.findById(req.payload.id).then(function(user){
    if(!user){ return res.sendStatus(401); }
    return res.json({user: user.toAuthJSON()});
  }).catch(next);
});

router.put('/user', auth.required, function(req, res, next){
  User.findById(req.payload.id).then(function(user){
    if(!user){ return res.sendStatus(401); }

    // only update fields that were actually passed...
    if(typeof req.body.user.username !== 'undefined'){
      user.username = req.body.user.username;
    }
    if(typeof req.body.user.email !== 'undefined'){
      user.email = req.body.user.email;
    }
    if(typeof req.body.user.bio !== 'undefined'){
      user.bio = req.body.user.bio;
    }
    if(typeof req.body.user.image !== 'undefined'){
      user.image = req.body.user.image;
    }
    if(typeof req.body.user.password !== 'undefined'){
      user.setPassword(req.body.user.password);
    }

    return user.save().then(function(){
      return res.json({user: user.toAuthJSON()});
    });
  }).catch(next);
});

router.post('/users/login', function(req, res, next){
  console.log(req.body.user)
  if(!req.body.user.phoneOrEmail){
    return res.status(422).json({errors: {phoneOrEmail: "can't be blank"}});
  }

  if(!req.body.user.password){
    return res.status(422).json({errors: {password: "can't be blank"}});
  }

  passport.authenticate('local', {session: false}, function(err, user, info){
    if(err){ return next(err); }

    if(user){
      user.token = user.generateJWT();
      return res.json({user: user.toAuthJSON()});
    } else {
      return res.status(422).json(info);
    }
  })(req, res, next);
});

router.post('/users', function(req, res, next){
  console.log("In Users now!")
  var email = req.body.user.email;
  var phone = req.body.user.phone;
  var username = null;
  var query = {};
  if (email && !phone) {
    username = email;
    query = {email: email};
    emailVerCode = randomNumber(4);
  }
  else if (email && phone) {
    username = email;
    query = { $or: [{email: email}, {phone: phone}]};
    phoneVerCode= randomNumber(4);
  }
  else {
    username = phone;
    query = {phone: phone};
    phoneVerCode= randomNumber(4);
  }
  User.findOne(query, function(err, returned){
    if(err) {
      return res.status(500).json(err);
    }
    if(returned){
      if(returned.username == email.toLowerCase()) {
        return res.status(422).json({errors: {email: "Email address is already registered."}});
      }
      else if (existingUser.phone == phone) {
        return res.status(422).json({errors: {phone: "Phone number is already registered."}});
      }
    }
    else {
      var user = new User();
      user.username = username;
      user.email = email;
      user.phone = phone;
      user.name = req.body.user.name;
      user.setPassword(req.body.user.password);
      user.save().then(function(){
        return res.json({user: user.toAuthJSON()});
      }).catch(next);
    }
  });
});

module.exports = router;
`

**Comment by mcblum** [comment]
I've got the same exact issue. Did you ever figure this out?

**Comment by nataCarballo** [comment]
I´ve got the same problem

**Comment by angelbrunn** [comment]
check this!

https://stackoverflow.com/questions/36558909/route-get-requires-callback-functions-but-got-a-object-undefined

**Comment by DaSilvaJr** [comment]
i have some problem like that :(

**Comment by jessicabyrne** [comment]
I had the same problem. Turned out I had a call in my router.js that wasn't available anymore. When I removed it, the error went away.

**Comment by wm1215** [comment]
@jessicabyrne can you clarify what call that you removed? Thanks.

**Comment by tonilaukka** [comment]
I was missing `module.exports = auth` at the end of `routes/api/users.js`

**Comment by Anindo94** [comment]
anyone please provide the solution

**Comment by eawww** [comment]
Check imports/requires and their respective exports for the `use` function's second argument and make sure they match up. In my case, I made the dumb mistake of doing a named import on a component that didn't have named exports.
i.e.: 
`export default ReallyNeatComponent`
`import { ReallyNeatComponent } from './ReallyNeatComponent'`

**Comment by Fathma** [comment]
In routes.js you might have called a function which doesn't exist in controller.js. make sure you have created all the functions that you are calling at the time of setting route.

**Comment by MRJordanGracia** [comment]
Hello 

> I was getting same problem.
> 
> My authenticate file has method:
> exports.verifyUser = passport.authenticate('jwt', {session: false});
> exports.verifyAdminUser = (req, res, next) => {
> 
> And my router file was:
> 
> uploadRouter.route('/')
> .get(authenticate.verifyUser, authenticate.verifyAdmin, (req, res, next) => {
> res.statusCode = 403;
> res.end('GET operation not supported on /imageUpload');
> })
> 
> It was unable to find the function authenticate.verifyAdmin when i change it to authenticate.verifyAdminUser it worked.
> 
> So you might be missing a function which is required while setting the routes/middleware.
Hello, could you tell me how you implemented the function of verifyAdmin, I'm having de same problem and I'm not able to see how to solve it.
Regards.

**Comment by hakoemmy** [comment]
@eawww You made my day. I was mixing `module.exporsts = auth` with `export default router`, after I choose to use one and it works like charm..

**Comment by dh360** [comment]
in my case , i write a wrong function name , it  happened

**Comment by proxybee** [comment]
> I had the same problem. Turned out I had a call in my router.js that wasn't available anymore. When I removed it, the error went away.

this worked for me too, thank you

**Comment by thurnye** [comment]
check your syntax in your controller, i had that problem for hrs getting pissed off. turns out it was just a syntax error " }"

**Comment by Jood80** [comment]
I got the same problem, the middleware was exported that way
`exports.isAuthenticated = (req, res, next) => {....}`
when I replaced it with 
` const isAuthenticated=(req, res, next)=>{.....}; 
 module.exports = isAuthenticated
`
it works for me

**Comment by md1116** [comment]
> anyone please provide the solution

I had the same issue and my mistake was using in express 
exports = {somefunctionName, anotherFunctionName}_ 
But looking at the above solution I did it like this and it works for me
**module.exports = {somefunctionName, anotherFunctionName}**

**Comment by zarateganso10** [comment]
i had the same issue, and my mistake was exporting the controller like a function and not a new object

module.exports = UserController   wrong way

module.exports = new UserController()     correct

**Comment by ya332** [comment]
I had the same issue and my problem was that I added .default in my require.
file_a
module.exports = dosomething
file_b
I changed this 
```js
const dosomething = require('file_a').default
```
to this 
```js
const dosomething = require('file_a')
```
and it fixed.

**Comment by ypedroo** [comment]
> i had the same issue, and my mistake was exporting the controller like a function and not a new object
> 
> module.exports = UserController wrong way
> 
> module.exports = new UserController() correct

Reading this i cant belive how stupid i was by loosing 2 hours on this haha, thank you dude

**Comment by lucaslp16** [comment]
Obtive o mesmo problema.
Eu invoquei um middleware para a rota, porem havia colocado o module.exports do middleware dentro da indentação do código, mania de ficar dando enter para dar mais espaço na tela kkk

Fiquei feliz por descobrir o problema porem puto pq perdi uns 30min procurando kkk

**Comment by kamaleshsivaraj** [comment]
Error: Route.get() requires a callback function but got a [object Undefined]  at Route.<computed> [as get] (node_modules) path

Instead of this:

`app.get('/user/all',Controller.Create);`
You try for:

```
app.get('/user/all', function(req, res){
  Controller.Create
});
```

it worked for me! after a 15mins

**Comment by hiranyagarbh** [comment]
> @eawww You made my day. I was mixing `module.exporsts = auth` with `export default router`, after I choose to use one and it works like charm..

Thank you for pointing that out. I was doing the same.

**Comment by yysach** [comment]
> > anyone please provide the solution
> 
> I had the same issue and my mistake was using in express
> exports = {somefunctionName, anotherFunctionName}_
> But looking at the above solution I did it like this and it works for me
> **module.exports = {somefunctionName, anotherFunctionName}**

thanks, I was doing the same mistake...

**Comment by Gichohi-Simon** [comment]
> I got the same problem, the middleware was exported that way
> `exports.isAuthenticated = (req, res, next) => {....}`
> when I replaced it with
> `const isAuthenticated=(req, res, next)=>{.....}; module.exports = isAuthenticated`
> it works for me

`

this works I have tried it in my code. Thanks a lot, but do you an idea why?

**Comment by malkashlomowithz** [comment]
> @eawww You made my day. I was mixing `module.exporsts = auth` with `export default router`, after I choose to use one and it works like charm..

Made my day too!!

**Comment by Rajveerbi** [comment]
just check if you are importig your functions properly on the routes and check the spellings

**Comment by nurulhiidayah** [comment]
in my case i accidentally put () for a middleware that did not accept params lol

**Comment by imranfarhat** [comment]
C:\Users\dell\OneDrive\Desktop\liftech\BackendLiftech\node_modules\express\lib\router\route.js:202
        throw new Error(msg);
        ^

Error: Route.get() requires a callback function but got a [object Undefined]
    at Route.<computed> [as get] (C:\Users\dell\OneDrive\Desktop\liftech\BackendLiftech\node_modules\express\lib\router\route.js:202:15)
    at Function.proto.<computed> [as get] (C:\Users\dell\OneDrive\Desktop\liftech\BackendLiftech\node_modules\express\lib\router\index.js:510:19)
    at Object.<anonymous> (C:\Users\dell\OneDrive\Desktop\liftech\BackendLiftech\routes\wallethistory.js:19:8)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (C:\Users\dell\OneDrive\Desktop\liftech\BackendLiftech\app.js:32:30)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
[nodemon] app crashed - waiting for file changes before starting...

**Comment by Jood80** [comment]
@imranfarhat you should post a snippet of your code that's complaining about too

**Comment by jagthapsaurabh** [comment]
\node\places-with-controllers\node_modules\express\lib\router\route.js:202
        throw new Error(msg);
        ^

Error: Route.get() requires a callback function but got a [object Undefined]
    at Route.<computed> [as get] (E:\full_stack_developer\node\places-with-controllers\node_modules\express\lib\router\route.js:202:15)
    at Function.proto.<computed> [as get] (E:\full_stack_developer\node\places-with-controllers\node_modules\express\lib\router\index.js:516:19)
    at Object.<anonymous> (E:\full_stack_developer\node\places-with-controllers\routes\place-routes.js:6:8)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (E:\full_stack_developer\node\places-with-controllers\index.js:4:22)
[nodemon] app crashed - waiting for file changes before starting...
![error](https://user-images.githubusercontent.com/95201228/147648601-aa40e933-3cba-447c-adbd-7b3cb934351f.png)

**Comment by ferisetiawan69** [comment]
Error: Route.post() requires a callback function but got a [object Object]

How to fix this?

**Comment by hilmidemirtas** [comment]
the problem is pageRoute or your Route.js file. Check or write again

**Comment by tsmith-sdm** [comment]
In my case I typod handler: as hander:

**Comment by airKing05** [comment]
got the same error currently using Node.js v18.1.0
I have cloned a 9-month-old project from the git repo
please help me to finger out it.

**Comment by Pvpasall** [comment]
Hi,
I got the same issue,
Check if you correctely import your controller

**Comment by G-rizz** [comment]
Hello..
I think I came acroos a solutin

**Comment by G-rizz** [comment]
Hi..
This issue actually bothered me for months so I will put my solution here to hopefully help someone. 

So, I am building a backend using express and es6 class based controllers. So I got this issue when I was creating the controller. 

You have to make sure that u are exporting AND importing your controller correctly.

On my part I was exporting using -export default Controller- as an example. 
 I realised that my problem happened when I was importing...
you import by saying " import Controller from '../controllers/..' "

I found out that my problem was that after this step I missed something very important.. 
You are supposed to create an instance of the class so that u can have access to the various functions in your class.. so I had to do that by adding

const controller = new Controller()

After doing that, I had access to the functions in the class and the warning disappeared. 

I hope this helps someone.
Goodluck

**Comment by Lanzero17** [comment]
### **@gothinkster**

The error is in the path:  **C:\production apps\backend\routes\api\users.js**  on line 9  

Check if you have a function like the following


router.get("/test-route",  **callback function** );

for example:

router.get("/test-route", **(req, res) => {
    return res.status(200).json({
        mensaje: "Soy una acción de prueba en mi controlador de articulos"
    })
}**);

### in case the callback function is imported from another module, make sure you are writing the export statement correctly, for example:

**//file users.js**-------------

const expres = require("express")
const router = expres.Router();

const ItemController = require("../controllers/item");
router.get("/test-route",  **callback function imported from another module** );



**//file that exports the callback function  example.js**-------------

const test = (req, res) => {
    return res.status(200).json({
        message: "I am a test action in my item controller"
    });
} 


**//Error made**
**//module.export is misspelled**
**//the import will not be carried out**

module.export = {
    test
}

**//The correct way to write is**

module.export**s**= {
    test
}

**My recommendation is that you check that each sentence is written correctly**

**Comment by davixie** [comment]
> Error: Route.get() requires a callback function but got a [object Undefined] at Route. [as get] (node_modules) path
> 
> Instead of this:
> 
> `app.get('/user/all',Controller.Create);` You try for:
> 
> ```
> app.get('/user/all', function(req, res){
>   Controller.Create
> });
> ```
> 
> it worked for me! after a 15mins

This worked for me too. Does anyone know why the first way is incorrect? It seems ok to me

**Comment by katsisaac50** [comment]
Always ensure the export name is the same as the import name

**Comment by anshu1016** [comment]
I encountered the same issue and resolved it by meticulously reviewing my import and export statements for every file and function. This turned out to be one of the causes leading to the problem.

**Comment by bloodhound-kurtis** [comment]
@Fathma https://lnkr.fun/190bf36
